name: reworkmobile
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0' # Ensure correct version constraint format

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.1
  flutter_tts: ^3.4.0 
  permission_handler: ^10.2.0
  #http: any
  speech_to_text: ^7.0.0 # For voice-to-text functionality
  image_picker: ^1.1.2
  image: ^4.5.2
  google_fonts: ^6.1.0 
  lucide_icons: ^0.257.0
  flutter_image_compress: ^2.4.0
  video_player: ^2.9.3
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ihear_logo.png
    - assets/hand_wave.png
    - assets/logo.png
    - assets/bgatas.png
    
    - assets/scan_icon.png
    - assets/lesson_icon.png
    - assets/voice_icon.png
    - assets/background_lesson1.png
