// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBflLuz9h-RcnH4UID5DseMoN-GxwBTxV0',
    appId: '1:897520395569:android:2502aa5bcbb89adaa2fc10',
    messagingSenderId: '897520395569',
    projectId: 'ihear-64527',
    storageBucket: 'ihear-64527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVXZLfH-XCu5V-3d7WGoCgCCJdJ7P8GXo',
    appId: '1:654450765799:ios:97f6bedc1479eca5261742',
    messagingSenderId: '654450765799',
    projectId: 'ihear-frontend',
    storageBucket: 'ihear-frontend.firebasestorage.app',
    iosBundleId: 'com.example.reworkmobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3LCHuhdzdrZ7vR7cOdlyry1BBnbcnx6I',
    appId: '1:654450765799:web:89286765000d25fb261742',
    messagingSenderId: '654450765799',
    projectId: 'ihear-frontend',
    authDomain: 'ihear-frontend.firebaseapp.com',
    storageBucket: 'ihear-frontend.firebasestorage.app',
    measurementId: 'G-13E1KX90QN',
  );

}