name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full clone for better analysis

      # Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Change if needed

      # Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Build APK
      - name: Build APK
        run: flutter build apk

      # Run SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Uncomment the following line if using self-hosted SonarQube
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
