name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # --- [1] Checkout Source Code ---
    - name: Checkout repository
      uses: actions/checkout@v3

    # --- [2] Setup Flutter SDK ---
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.4' # atau 'stable'

    # --- [3] Continuous Integration: Install dependencies ---
    - name: Install dependencies
      run: flutter pub get

    # --- [4A] Continuous Inspection: Analyze code style and issues ---
    - name: Analyze code
      run: flutter analyze

    # --- [4B] Optional: Check formatting ---
    - name: Check formatting
      run: dart format --set-exit-if-changed .

    # --- [5] Continuous Testing: Run automated tests ---
    - name: Unit Testing
      run: flutter test test/unit_test/main_unit_test.dart

    # --- [6] Continuous Deployment/Delivery: Build debug APK ---
    - name: Build APK (debug)
      run: flutter build apk --debug
