# A name for the entire workflow
name: Build, Release and Distribute

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  # A single job that will perform all our steps
  build-and-release:
    runs-on: ubuntu-latest

    #===================================================================#
    # THIS IS THE FIX. It's not a secret, it's a permission setting. #
    # This gives the automatic GITHUB_TOKEN the power to create a release. #
    permissions:
      contents: write
    #===================================================================#

    steps:
      # 1. Checks out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Java, which is required for Android builds
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Set up Flutter using the 'beta' channel
      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: 'beta'

      # 4. Installs your app's dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # 5. Build APK
      - name: Build APK
        run: flutter build apk --release

      # 6. Build AAB
      - name: Build AAB
        run: flutter build appbundle --release

      # --- Distribution Steps ---

      # 7. Distribute APK to Firebase Testers
      - name: Distribute to Firebase App Distribution
        run: |
          curl -sL https://firebase.tools | bash
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app "${{ secrets.FIREBASE_APP_ID }}" \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            --release-notes "New test build. Also available on GitHub Release v${{ github.run_number }}." \
            --testers "rdmfaisalrj@gmail.com,daniel.budi.babakan@gmail.com, unknownhaha677@gmail.com, fajarmufid01@gmail.com, purianagatha@gmail.com"

      # 8. Create a Public GitHub Release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.run_number }}
          name: "iHear v${{ github.run_number }}"
          body: "Automated release. This build was also sent to testers via Firebase."
          artifacts: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          token: ${{ secrets.GITHUB_TOKEN }} # This uses the magic, automatic token
